---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This was my part in the class project, making a Covid Shiny App
```{r}


#order the number of cases for each state by date and calculate death/cases     ratio by day, 
#stored in new$ratio. highest ratio is found by state and sorted in         peak_sorted
usstates <- NYTimes_US_States_Historical_Data
new <- usstates[order(usstates$state),]
new$ratio <- new$deaths/new$cases
peak_sorted <- new %>% group_by(state) %>% filter(ratio == max(ratio))
  
  
#national deaths/cases
new_national <- NYTimes_US_Historical_Data
new_national$ratio <- new_national$deaths/new_national$cases
  
#comparing latest ratio of deaths/cases by state and in the entire country
latest_ratio_states <- new %>% filter(date==max(date))
latest_ratio_national <- new_national %>% filter(date==max(date))
comparison_latest <- ifelse(latest_ratio_states$ratio >= test = latest_ratio_national$ratio, 1, 0)
combined_latest <- cbind(latest_ratio_states, comparison_latest)
  
  
#plot the states' latest deaths/cases ratio
output$latestplot <- renderPlot({
plot_latest <- plot_usmap("states", data = combined_latest, values = "ratio", color = "black", labels = TRUE) + scale_fill_continuous(low = "white", high = " red", name = "Latest Deaths/Cases Ratio") + labs(title = "Latest Deaths/Cases Ratio") + theme(legend.position = "left")

return(plot_latest)
})

```
